nmsExchange.1.name=New York Stock Exchange
nmsExchange.1.acronym=NYSE
nmsExchange.1.location=New York NY
nmsExchange.1.ipAddress=127.0.0.1
nmsExchange.1.port=25001
nmsExchange.1.latencyAlert=50
nmsExchange.1.handlerName=fix
nmsExchange.1.connectionRetries=3
nmsExchange.1.connectionRetryInterval=3000
nmsExchange.1.connectionRecoveryBehavior=default
nmsExchange.1.connectionStartTime=0930
nmsExchange.1.connectionEndTime=1600
nmsExchange.1.connectionType=initiator
nmsExchange.1.senderCompID=GATEWAY
nmsExchange.1.targetCompID=EXCHANGE
nmsExchange.1.heartBtInt=30
nmsExchange.1.useDataDictionary=Y
nmsExchange.1.dataDictionary=FIX42.xml
nmsExchange.1.fileStorePath=store
nmsExchange.1.fileLogPath=log

nmsExchange.2.name=NYSE American LLC
nmsExchange.2.acronym=NYSE American
nmsExchange.2.location=New York NY
nmsExchange.2.ipAddress=127.0.0.1
nmsExchange.2.port=25002
nmsExchange.2.latencyAlert=50
nmsExchange.2.handlerName=json
nmsExchange.2.connectionRetries=3
nmsExchange.2.connectionRetryInterval=3000
nmsExchange.2.connectionRecoveryBehavior=default
nmsExchange.2.connectionStartTime=0930
nmsExchange.2.connectionEndTime=1600
nmsExchange.2.connectionType=initiator
nmsExchange.2.senderCompID=GATEWAY
nmsExchange.2.targetCompID=EXCHANGE
nmsExchange.2.heartBtInt=30
nmsExchange.2.useDataDictionary=Y
nmsExchange.2.dataDictionary=FIX42.xml
nmsExchange.2.fileStorePath=store
nmsExchange.2.fileLogPath=log

nmsExchange.3.name=NYSE Arca Inc
nmsExchange.3.acronym=NYSE Arca
nmsExchange.3.location=Chicago IL / New York NY
nmsExchange.3.ipAddress=127.0.0.1
nmsExchange.3.port=25003
nmsExchange.3.latencyAlert=50
nmsExchange.3.handlerName=fix
nmsExchange.3.connectionRetries=3
nmsExchange.3.connectionRetryInterval=3000
nmsExchange.3.connectionRecoveryBehavior=default
nmsExchange.3.connectionStartTime=0930
nmsExchange.3.connectionEndTime=1600
nmsExchange.3.connectionType=initiator
nmsExchange.3.senderCompID=GATEWAY
nmsExchange.3.targetCompID=EXCHANGE
nmsExchange.3.heartBtInt=30
nmsExchange.3.useDataDictionary=Y
nmsExchange.3.dataDictionary=FIX42.xml
nmsExchange.3.fileStorePath=store
nmsExchange.3.fileLogPath=log

nmsExchange.4.name=NASDAQ Stock Market LLC
nmsExchange.4.acronym=NASDAQ
nmsExchange.4.location=New York NY
nmsExchange.4.ipAddress=127.0.0.1
nmsExchange.4.port=25004
nmsExchange.4.latencyAlert=50
nmsExchange.4.handlerName=fix
nmsExchange.4.connectionRetries=3
nmsExchange.4.connectionRetryInterval=3000
nmsExchange.4.connectionRecoveryBehavior=default
nmsExchange.4.connectionStartTime=0930
nmsExchange.4.connectionEndTime=1600
nmsExchange.4.connectionType=initiator
nmsExchange.4.senderCompID=GATEWAY
nmsExchange.4.targetCompID=EXCHANGE
nmsExchange.4.heartBtInt=30
nmsExchange.4.useDataDictionary=Y
nmsExchange.4.dataDictionary=FIX42.xml
nmsExchange.4.fileStorePath=store
nmsExchange.4.fileLogPath=log

nmsExchange.5.name=Investors Exchange LLC
nmsExchange.5.acronym=IEX
nmsExchange.5.location=New York NY
nmsExchange.5.ipAddress=127.0.0.1
nmsExchange.5.port=25005
nmsExchange.5.latencyAlert=50
nmsExchange.5.handlerName=fix
nmsExchange.5.connectionRetries=3
nmsExchange.5.connectionRetryInterval=3000
nmsExchange.5.connectionRecoveryBehavior=default
nmsExchange.5.connectionStartTime=0930
nmsExchange.5.connectionEndTime=1600
nmsExchange.5.connectionType=initiator
nmsExchange.5.senderCompID=GATEWAY
nmsExchange.5.targetCompID=EXCHANGE
nmsExchange.5.heartBtInt=30
nmsExchange.5.useDataDictionary=Y
nmsExchange.5.dataDictionary=FIX42.xml
nmsExchange.5.fileStorePath=store
nmsExchange.5.fileLogPath=log

nmsExchange.6.name=Long-Term Stock Exchange Inc
nmsExchange.6.acronym=LTSE
nmsExchange.6.location=San Francisco CA
nmsExchange.6.ipAddress=127.0.0.1
nmsExchange.6.port=25006
nmsExchange.6.latencyAlert=50
nmsExchange.6.handlerName=fix
nmsExchange.6.connectionRetries=3
nmsExchange.6.connectionRetryInterval=3000
nmsExchange.6.connectionRecoveryBehavior=default
nmsExchange.6.connectionStartTime=0930
nmsExchange.6.connectionEndTime=1600
nmsExchange.6.connectionType=initiator
nmsExchange.6.senderCompID=GATEWAY
nmsExchange.6.targetCompID=EXCHANGE
nmsExchange.6.heartBtInt=30
nmsExchange.6.useDataDictionary=Y
nmsExchange.6.dataDictionary=FIX42.xml
nmsExchange.6.fileStorePath=store
nmsExchange.6.fileLogPath=log

nmsExchange.7.name=MEMX LLC
nmsExchange.7.acronym=MEMX
nmsExchange.7.location=Jersey City NJ
nmsExchange.7.ipAddress=127.0.0.1
nmsExchange.7.port=25007
nmsExchange.7.latencyAlert=50
nmsExchange.7.handlerName=fix
nmsExchange.7.connectionRetries=3
nmsExchange.7.connectionRetryInterval=3000
nmsExchange.7.connectionRecoveryBehavior=default
nmsExchange.7.connectionStartTime=0930
nmsExchange.7.connectionEndTime=1600
nmsExchange.7.connectionType=initiator
nmsExchange.7.senderCompID=GATEWAY
nmsExchange.7.targetCompID=EXCHANGE
nmsExchange.7.heartBtInt=30
nmsExchange.7.useDataDictionary=Y
nmsExchange.7.dataDictionary=FIX42.xml
nmsExchange.7.fileStorePath=store
nmsExchange.7.fileLogPath=log

nmsExchange.8.name=MIAX Pearl LLC
nmsExchange.8.acronym=MIAX Pearl
nmsExchange.8.location=Princeton NJ
nmsExchange.8.ipAddress=127.0.0.1
nmsExchange.8.port=25008
nmsExchange.8.latencyAlert=50
nmsExchange.8.handlerName=fix
nmsExchange.8.connectionRetries=3
nmsExchange.8.connectionRetryInterval=3000
nmsExchange.8.connectionRecoveryBehavior=default
nmsExchange.8.connectionStartTime=0930
nmsExchange.8.connectionEndTime=1600
nmsExchange.8.connectionType=initiator
nmsExchange.8.senderCompID=GATEWAY
nmsExchange.8.targetCompID=EXCHANGE
nmsExchange.8.heartBtInt=30
nmsExchange.8.useDataDictionary=Y
nmsExchange.8.dataDictionary=FIX42.xml
nmsExchange.8.fileStorePath=store
nmsExchange.8.fileLogPath=log

nmsExchange.9.name=MIAX Emerald LLC
nmsExchange.9.acronym=MIAX Emerald
nmsExchange.9.location=Princeton NJ
nmsExchange.9.ipAddress=127.0.0.1
nmsExchange.9.port=25009
nmsExchange.9.latencyAlert=50
nmsExchange.9.handlerName=fix
nmsExchange.9.connectionRetries=3
nmsExchange.9.connectionRetryInterval=3000
nmsExchange.9.connectionRecoveryBehavior=default
nmsExchange.9.connectionStartTime=0930
nmsExchange.9.connectionEndTime=1600
nmsExchange.9.connectionType=initiator
nmsExchange.9.senderCompID=GATEWAY
nmsExchange.9.targetCompID=EXCHANGE
nmsExchange.9.heartBtInt=30
nmsExchange.9.useDataDictionary=Y
nmsExchange.9.dataDictionary=FIX42.xml
nmsExchange.9.fileStorePath=store
nmsExchange.9.fileLogPath=log

nmsExchange.10.name=MIAX Exchange LLC
nmsExchange.10.acronym=MIAX
nmsExchange.10.location=Princeton NJ
nmsExchange.10.ipAddress=127.0.0.1
nmsExchange.10.port=25010
nmsExchange.10.latencyAlert=50
nmsExchange.10.handlerName=fix
nmsExchange.10.connectionRetries=3
nmsExchange.10.connectionRetryInterval=3000
nmsExchange.10.connectionRecoveryBehavior=default
nmsExchange.10.connectionStartTime=0930
nmsExchange.10.connectionEndTime=1600
nmsExchange.10.connectionType=initiator
nmsExchange.10.senderCompID=GATEWAY
nmsExchange.10.targetCompID=EXCHANGE
nmsExchange.10.heartBtInt=30
nmsExchange.10.useDataDictionary=Y
nmsExchange.10.dataDictionary=FIX42.xml
nmsExchange.10.fileStorePath=store
nmsExchange.10.fileLogPath=log

nmsExchange.11.name=Cboe Exchange Inc
nmsExchange.11.acronym=CBOE
nmsExchange.11.location=Chicago IL
nmsExchange.11.ipAddress=127.0.0.1
nmsExchange.11.port=25011
nmsExchange.11.latencyAlert=50
nmsExchange.11.handlerName=fix
nmsExchange.11.connectionRetries=3
nmsExchange.11.connectionRetryInterval=3000
nmsExchange.11.connectionRecoveryBehavior=default
nmsExchange.11.connectionStartTime=0930
nmsExchange.11.connectionEndTime=1600
nmsExchange.11.connectionType=initiator
nmsExchange.11.senderCompID=GATEWAY
nmsExchange.11.targetCompID=EXCHANGE
nmsExchange.11.heartBtInt=30
nmsExchange.11.useDataDictionary=Y
nmsExchange.11.dataDictionary=FIX42.xml
nmsExchange.11.fileStorePath=store
nmsExchange.11.fileLogPath=log

nmsExchange.12.name=Cboe BYX Exchange Inc
nmsExchange.12.acronym=CBOE BYX
nmsExchange.12.location=Kansas City MO
nmsExchange.12.ipAddress=127.0.0.1
nmsExchange.12.port=25012
nmsExchange.12.latencyAlert=50
nmsExchange.12.handlerName=fix
nmsExchange.12.connectionRetries=3
nmsExchange.12.connectionRetryInterval=3000
nmsExchange.12.connectionRecoveryBehavior=default
nmsExchange.12.connectionStartTime=0930
nmsExchange.12.connectionEndTime=1600
nmsExchange.12.connectionType=initiator
nmsExchange.12.senderCompID=GATEWAY
nmsExchange.12.targetCompID=EXCHANGE
nmsExchange.12.heartBtInt=30
nmsExchange.12.useDataDictionary=Y
nmsExchange.12.dataDictionary=FIX42.xml
nmsExchange.12.fileStorePath=store
nmsExchange.12.fileLogPath=log

nmsExchange.13.name=Cboe BZX Exchange Inc
nmsExchange.13.acronym=CBOE BZX
nmsExchange.13.location=Kansas City MO
nmsExchange.13.ipAddress=127.0.0.1
nmsExchange.13.port=25013
nmsExchange.13.latencyAlert=50
nmsExchange.13.handlerName=fix
nmsExchange.13.connectionRetries=3
nmsExchange.13.connectionRetryInterval=3000
nmsExchange.13.connectionRecoveryBehavior=default
nmsExchange.13.connectionStartTime=0930
nmsExchange.13.connectionEndTime=1600
nmsExchange.13.connectionType=initiator
nmsExchange.13.senderCompID=GATEWAY
nmsExchange.13.targetCompID=EXCHANGE
nmsExchange.13.heartBtInt=30
nmsExchange.13.useDataDictionary=Y
nmsExchange.13.dataDictionary=FIX42.xml
nmsExchange.13.fileStorePath=store
nmsExchange.13.fileLogPath=log

nmsExchange.14.name=Cboe EDGA Exchange Inc
nmsExchange.14.acronym=CBOE EDGA
nmsExchange.14.location=Kansas City MO
nmsExchange.14.ipAddress=127.0.0.1
nmsExchange.14.port=25014
nmsExchange.14.latencyAlert=50
nmsExchange.14.handlerName=fix
nmsExchange.14.connectionRetries=3
nmsExchange.14.connectionRetryInterval=3000
nmsExchange.14.connectionRecoveryBehavior=default
nmsExchange.14.connectionStartTime=0930
nmsExchange.14.connectionEndTime=1600
nmsExchange.14.connectionType=initiator
nmsExchange.14.senderCompID=GATEWAY
nmsExchange.14.targetCompID=EXCHANGE
nmsExchange.14.heartBtInt=30
nmsExchange.14.useDataDictionary=Y
nmsExchange.14.dataDictionary=FIX42.xml
nmsExchange.14.fileStorePath=store
nmsExchange.14.fileLogPath=log

nmsExchange.15.name=Cboe EDGX Exchange Inc
nmsExchange.15.acronym=CBOE EDGX
nmsExchange.15.location=Kansas City MO
nmsExchange.15.ipAddress=127.0.0.1
nmsExchange.15.port=25015
nmsExchange.15.latencyAlert=50
nmsExchange.15.handlerName=fix
nmsExchange.15.connectionRetries=3
nmsExchange.15.connectionRetryInterval=3000
nmsExchange.15.connectionRecoveryBehavior=default
nmsExchange.15.connectionStartTime=0930
nmsExchange.15.connectionEndTime=1600
nmsExchange.15.connectionType=initiator
nmsExchange.15.senderCompID=GATEWAY
nmsExchange.15.targetCompID=EXCHANGE
nmsExchange.15.heartBtInt=30
nmsExchange.15.useDataDictionary=Y
nmsExchange.15.dataDictionary=FIX42.xml
nmsExchange.15.fileStorePath=store
nmsExchange.15.fileLogPath=log

nmsExchange.16.name=Cboe C2 Exchange Inc
nmsExchange.16.acronym=CBOE C2
nmsExchange.16.location=Chicago IL
nmsExchange.16.ipAddress=127.0.0.1
nmsExchange.16.port=25016
nmsExchange.16.latencyAlert=50
nmsExchange.16.handlerName=fix
nmsExchange.16.connectionRetries=3
nmsExchange.16.connectionRetryInterval=3000
nmsExchange.16.connectionRecoveryBehavior=default
nmsExchange.16.connectionStartTime=0930
nmsExchange.16.connectionEndTime=1600
nmsExchange.16.connectionType=initiator
nmsExchange.16.senderCompID=GATEWAY
nmsExchange.16.targetCompID=EXCHANGE
nmsExchange.16.heartBtInt=30
nmsExchange.16.useDataDictionary=Y
nmsExchange.16.dataDictionary=FIX42.xml
nmsExchange.16.fileStorePath=store
nmsExchange.16.fileLogPath=log

nmsExchange.17.name=BOX Exchange LLC
nmsExchange.17.acronym=BOX
nmsExchange.17.location=Boston MA
nmsExchange.17.ipAddress=127.0.0.1
nmsExchange.17.port=25017
nmsExchange.17.latencyAlert=50
nmsExchange.17.handlerName=fix
nmsExchange.17.connectionRetries=3
nmsExchange.17.connectionRetryInterval=3000
nmsExchange.17.connectionRecoveryBehavior=default
nmsExchange.17.connectionStartTime=0930
nmsExchange.17.connectionEndTime=1600
nmsExchange.17.connectionType=initiator
nmsExchange.17.senderCompID=GATEWAY
nmsExchange.17.targetCompID=EXCHANGE
nmsExchange.17.heartBtInt=30
nmsExchange.17.useDataDictionary=Y
nmsExchange.17.dataDictionary=FIX42.xml
nmsExchange.17.fileStorePath=store
nmsExchange.17.fileLogPath=log

nmsExchange.18.name=24X National Exchange LLC
nmsExchange.18.acronym=24X
nmsExchange.18.location=Miami FL
nmsExchange.18.ipAddress=127.0.0.1
nmsExchange.18.port=25018
nmsExchange.18.latencyAlert=50
nmsExchange.18.handlerName=fix
nmsExchange.18.connectionRetries=3
nmsExchange.18.connectionRetryInterval=3000
nmsExchange.18.connectionRecoveryBehavior=default
nmsExchange.18.connectionStartTime=0930
nmsExchange.18.connectionEndTime=1600
nmsExchange.18.connectionType=initiator
nmsExchange.18.senderCompID=GATEWAY
nmsExchange.18.targetCompID=EXCHANGE
nmsExchange.18.heartBtInt=30
nmsExchange.18.useDataDictionary=Y
nmsExchange.18.dataDictionary=FIX42.xml
nmsExchange.18.fileStorePath=store
nmsExchange.18.fileLogPath=log

nmsExchange.19.name=Green Impact Exchange LLC
nmsExchange.19.acronym=GIX
nmsExchange.19.location=Chicago IL
nmsExchange.19.ipAddress=127.0.0.1
nmsExchange.19.port=25019
nmsExchange.19.latencyAlert=50
nmsExchange.19.handlerName=fix
nmsExchange.19.connectionRetries=3
nmsExchange.19.connectionRetryInterval=3000
nmsExchange.19.connectionRecoveryBehavior=default
nmsExchange.19.connectionStartTime=0930
nmsExchange.19.connectionEndTime=1600
nmsExchange.19.connectionType=initiator
nmsExchange.19.senderCompID=GATEWAY
nmsExchange.19.targetCompID=EXCHANGE
nmsExchange.19.heartBtInt=30
nmsExchange.19.useDataDictionary=Y
nmsExchange.19.dataDictionary=FIX42.xml
nmsExchange.19.fileStorePath=store
nmsExchange.19.fileLogPath=log